apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: agasa-admin
  labels:
    cloud.googleapis.com/location: europe-west1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1' # Contre le cold start
        autoscaling.knative.dev/maxScale: '10'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: europe-west1-docker.pkg.dev/PROJECT_ID/agasa-repo/agasa-admin:latest
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NEXT_PUBLIC_CONVEX_URL
          value: "URL_A_INJECTER_PAR_SECRET_MANAGER"
        - name: NEXT_PUBLIC_FIREBASE_API_KEY
          value: "URL_A_INJECTER_PAR_SECRET_MANAGER"
        - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
          value: "URL_A_INJECTER_PAR_SECRET_MANAGER"
        - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
          value: "URL_A_INJECTER_PAR_SECRET_MANAGER"
